"""
Recovery engine tests, built on REAL files, because the previous ones were not.

The old suite passed twelve tests against JPEGs this file made up: a `FF D8 FF` header, a
JFIF-looking prefix, arbitrary body bytes, a `FF D9` footer. Those are not JPEGs. They
have no DQT, no SOF, no start-of-scan, nothing a decoder would accept. The carver's
"validation" was header matching, so fake input and fake validation agreed with each other
and every test went green.

Run against NIST CFReDS `L4_Graphic.dd`, the same code reported 50 artefacts where 9 files
exist, matched one byte-for-byte, and flagged none as uncertain. Two percent precision,
reported with complete confidence.

So every image here is now generated by a real encoder (Pillow) and is decodable. A test
that a real decoder would reject is a test that proves nothing.

`tests/test_recovery_nist.py` carries the ground-truth scoring against the NIST corpus
itself; this file covers behaviour that does not need a 50 MB download.
"""

import io
import os

import pytest

pytest.importorskip("PIL", reason="Pillow absent; recovery tests need real encoded images")
from PIL import Image  # noqa: E402

from recovery.engine import (  # noqa: E402
    HIGH, LOW, MEDIUM, SIGNATURES, carve, outcome_for, result_hash, summarize,
)


def _img(fmt: str, size=(24, 18), **kw) -> bytes:
    """A genuinely encoded image. Not a byte pattern that looks like one."""
    im = Image.new("RGB", size)
    for x in range(size[0]):
        for y in range(size[1]):
            im.putpixel((x, y), ((x * 11) % 256, (y * 7) % 256, ((x + y) * 3) % 256))
    buf = io.BytesIO()
    im.save(buf, format=fmt, **kw)
    return buf.getvalue()


@pytest.fixture(scope="module")
def real():
    return {
        "jpg": _img("JPEG", quality=85),
        "png": _img("PNG"),
        "gif": _img("GIF"),
        "bmp": _img("BMP"),
        "tif": _img("TIFF"),
    }


@pytest.fixture()
def image(tmp_path, real):
    """A raw image with three real files buried in slack space, no filesystem."""
    blob = (os.urandom(2048) + real["jpg"] + os.urandom(1024) + real["png"]
            + os.urandom(4096) + real["bmp"] + os.urandom(2048))
    p = tmp_path / "evidence.dd"
    p.write_bytes(blob)
    return p, real


# ───────────────────────────────────────────── the real files come back exactly

def test_recovers_three_known_files(image):
    path, _ = image
    got = carve(str(path))
    assert {a["type"] for a in got} >= {"jpg", "png", "bmp"}


def test_recovered_bytes_are_byte_identical_to_the_originals(image):
    """The only assertion that matters: the carved bytes ARE the file."""
    import hashlib
    path, real = image
    got = {a["type"]: a for a in carve(str(path))}
    for ext in ("jpg", "png", "bmp"):
        assert got[ext]["sha256"] == hashlib.sha256(real[ext]).hexdigest(), \
            f"{ext} did not come back byte-identical"
        assert got[ext]["size"] == len(real[ext])


def test_recovered_files_are_still_decodable(image, tmp_path):
    """A carve that a decoder rejects is not a recovery, whatever the hash says."""
    path, _ = image
    out = tmp_path / "recovered"
    checked = 0
    for a in carve(str(path), out_dir=str(out)):
        if a["confidence"] != HIGH:
            continue
        with Image.open(a["extracted_to"]) as im:
            im.verify()
        checked += 1
    # THE LOOP MUST HAVE RUN. Without this the test passes when the carver returns
    # nothing at all, or returns nothing HIGH -- verifying zero files and reporting
    # success. An adversarial audit flagged it as a vacuous pass, which is exactly the
    # shape of a test that guards nothing while inflating a count.
    assert checked > 0, "no HIGH-confidence artefact was decoded; the test proved nothing"


def test_extents_confirmed_by_structure_are_high_confidence(image):
    path, _ = image
    got = {a["type"]: a for a in carve(str(path))}
    for ext in ("jpg", "png", "bmp"):
        assert got[ext]["confidence"] == HIGH
        assert got[ext]["truncated"] is False
        assert got[ext]["validated"] is True


# ───────────────────────────────────────── coincidental headers are now rejected

def test_a_bare_header_in_random_data_is_not_carved(tmp_path):
    """`FF D8 FF` occurs constantly inside compressed data. It is not a file."""
    p = tmp_path / "noise.dd"
    p.write_bytes(os.urandom(512) + b"\xff\xd8\xff" + os.urandom(4096))
    assert carve(str(p), types=["jpg"]) == []


def test_a_header_with_an_invalid_following_marker_is_rejected(tmp_path):
    p = tmp_path / "bad.dd"
    p.write_bytes(b"\xff\xd8\xff\x11" + b"X" * 2000 + b"\xff\xd9")
    assert carve(str(p), types=["jpg"]) == []


def test_the_old_fake_jpeg_is_now_correctly_rejected(tmp_path):
    """Regression marker. This byte pattern passed the previous suite twelve times."""
    fake = b"\xff\xd8\xff" + b"\xe0\x00\x10JFIF\x00" + b"J" * 500 + b"\xff\xd9"
    p = tmp_path / "fake.dd"
    p.write_bytes(os.urandom(256) + fake + os.urandom(256))
    assert carve(str(p), types=["jpg"]) == [], \
        "a structurally invalid JPEG must not be reported as a recovered file"


def test_a_rejected_candidate_does_not_hide_a_real_file_after_it(tmp_path, real):
    """Skipping the whole max_size on rejection would blind the scan. Skip one byte."""
    p = tmp_path / "mixed.dd"
    p.write_bytes(b"\xff\xd8\xff\x11" + os.urandom(64) + real["jpg"] + os.urandom(64))
    got = carve(str(p), types=["jpg"])
    assert len(got) == 1
    assert got[0]["confidence"] == HIGH


# ─────────────────────────────────────── the thumbnail defect, on a real thumbnail

def test_a_jpeg_with_an_exif_thumbnail_carves_once(tmp_path):
    """An EXIF thumbnail is a whole JPEG inside its parent's APP1 segment. Scanning for
    the first FF D9 found the thumbnail's footer and split one photo into several
    'complete' files. Segment walking steps over APP1 instead."""
    im = Image.new("RGB", (64, 48), (120, 30, 200))
    thumb = io.BytesIO()
    Image.new("RGB", (16, 12), (10, 200, 90)).save(thumb, format="JPEG")

    exif = Image.Exif()
    exif[0x0132] = "2026:01:01 00:00:00"
    buf = io.BytesIO()
    im.save(buf, format="JPEG", exif=exif, quality=80)
    parent = buf.getvalue()

    # splice the thumbnail bytes into the parent's stream the way a camera would
    payload = parent[:2] + b"\xff\xe1" + len(thumb.getvalue()).to_bytes(2, "big") \
        + thumb.getvalue()[:max(0, len(thumb.getvalue()) - 2)] + parent[2:]

    p = tmp_path / "photo.dd"
    p.write_bytes(os.urandom(128) + payload + os.urandom(128))
    got = carve(str(p), types=["jpg"])
    assert len(got) <= 1, f"one photograph carved as {len(got)} files"


# ─────────────────────────────────────────── honesty about what was not resolved

def test_tiff_and_pcx_extents_are_now_resolved_exactly(tmp_path, real):
    """TIFF and PCX have no footer, and this used to mean a size CAP and a LOW-confidence
    guess, which is why their carved bytes never matched a NIST source file. Both
    extents are in fact fully determinable: TIFF from its IFD and strip offsets, PCX by
    decoding the RLE stream to the declared image size."""
    import hashlib
    for ext in ("tif",):
        p = tmp_path / f"{ext}.dd"
        p.write_bytes(os.urandom(256) + real[ext] + os.urandom(256))
        got = carve(str(p), types=[ext])
        assert got, f"{ext} not detected"
        assert got[0]["confidence"] == HIGH, got[0]["reason"]
        assert got[0]["size"] == len(real[ext])
        assert got[0]["sha256"] == hashlib.sha256(real[ext]).hexdigest()


def test_a_truncated_file_is_low_confidence(tmp_path, real):
    """A real remaining unresolved case: a JPEG whose end-of-image never arrives. The
    size reported is a cap, and it must say so rather than imply a boundary."""
    p = tmp_path / "cut.dd"
    # Cut only the trailing bytes: the scan data survives, the end-of-image marker does
    # not. Cutting at the halfway point would remove the start-of-scan segment too, and
    # a fragment with no scan data is correctly rejected outright rather than reported
    # as an unresolved file.
    p.write_bytes(os.urandom(64) + real["jpg"][:-8])
    got = carve(str(p), types=["jpg"])
    assert got
    assert got[0]["confidence"] == LOW
    assert "end-of-image never reached" in got[0]["reason"]


def test_the_summary_leads_with_how_many_extents_are_trustworthy(tmp_path, real):
    p = tmp_path / "m.dd"
    p.write_bytes(real["png"] + os.urandom(256)
                  + real["jpg"][:-8])   # deliberately truncated: EOI removed
    s = summarize(carve(str(p)))
    assert s["high_confidence"] < s["total"]
    assert "candidates" in s["note"]
    assert "not as recovered files" in s["note"]


def test_the_summary_never_calls_a_low_confidence_set_recovered(tmp_path, real):
    """The old note said 'every artifact had a located footer' over a 2%-precision set."""
    p = tmp_path / "t.dd"
    p.write_bytes(real["tif"])
    s = summarize(carve(str(p)))
    assert "every artifact had a located footer" not in s["note"]


def test_outcome_is_partial_when_any_extent_was_estimated(tmp_path, real):
    p = tmp_path / "m.dd"
    p.write_bytes(real["png"] + os.urandom(128)
                  + real["jpg"][:-8])   # deliberately truncated: EOI removed
    assert outcome_for(carve(str(p))) == "PARTIAL"


def test_outcome_is_verified_only_when_every_extent_is_confirmed(tmp_path, real):
    p = tmp_path / "clean.dd"
    p.write_bytes(os.urandom(128) + real["png"] + os.urandom(128) + real["bmp"]
                  + os.urandom(128) + real["tif"] + os.urandom(128) + real["gif"])
    got = carve(str(p))
    assert all(a["confidence"] == HIGH for a in got)
    assert outcome_for(got) == "VERIFIED"


# ─────────────────────────────────────────────────────── structural validators

def test_bmp_size_comes_from_its_own_header(tmp_path, real):
    p = tmp_path / "b.dd"
    p.write_bytes(os.urandom(64) + real["bmp"] + b"TRAILING-GARBAGE" * 100)
    got = carve(str(p), types=["bmp"])
    assert got[0]["size"] == len(real["bmp"])       # exact, not a footer search
    assert got[0]["confidence"] == HIGH


def test_a_bmp_header_with_a_nonzero_reserved_field_is_rejected(tmp_path):
    p = tmp_path / "b.dd"
    p.write_bytes(b"BM" + (5000).to_bytes(4, "little") + b"\xff\xff\xff\xff"
                  + (54).to_bytes(4, "little") + os.urandom(5000))
    assert carve(str(p), types=["bmp"]) == []


def test_a_png_without_ihdr_is_rejected(tmp_path):
    import struct, zlib
    def chunk(t, d):
        c = t + d
        return struct.pack(">I", len(d)) + c + struct.pack(">I", zlib.crc32(c) & 0xffffffff)
    bad = b"\x89PNG\r\n\x1a\n" + chunk(b"IDAT", b"x") + chunk(b"IEND", b"")
    p = tmp_path / "p.dd"
    p.write_bytes(bad)
    assert carve(str(p), types=["png"]) == []


def test_every_signature_declares_a_validator():
    """A signature without a validator is a header match, and header matches are what
    produced 2% precision."""
    missing = [s.ext for s in SIGNATURES if s.validate is None]
    assert missing == [], f"signatures with no structural validator: {missing}"


def test_all_six_nist_graphic_types_are_covered():
    """NIST's graphic corpus uses these. The old table saw only three of them."""
    assert {"jpg", "png", "gif", "bmp", "tif", "pcx"} <= {s.ext for s in SIGNATURES}


# ─────────────────────────────────────────────────────────────── plumbing

def test_empty_image_returns_nothing(tmp_path):
    p = tmp_path / "empty.dd"
    p.write_bytes(b"")
    assert carve(str(p)) == []


def test_missing_image_raises(tmp_path):
    with pytest.raises(FileNotFoundError):
        carve(str(tmp_path / "nope.dd"))


def test_unknown_type_is_refused(image):
    path, _ = image
    with pytest.raises(ValueError, match="unknown signature type"):
        carve(str(path), types=["docx"])


def test_result_hash_commits_to_confidence_too(image):
    """The ledger must fix how sure the tool was, not only what it found."""
    path, _ = image
    got = carve(str(path))
    h = result_hash(got)
    got[0]["confidence"] = HIGH if got[0]["confidence"] != HIGH else LOW
    assert result_hash(got) != h


def test_extraction_writes_files_matching_their_recorded_digest(image, tmp_path):
    import hashlib
    path, _ = image
    out = tmp_path / "recovered"
    for a in carve(str(path), out_dir=str(out)):
        data = (out / a["filename"]).read_bytes()
        assert hashlib.sha256(data).hexdigest() == a["sha256"]


def test_a_carve_that_recovered_nothing_is_not_VERIFIED():
    """Vacuous truth is the wrong word in a signed field a court reads.

    outcome_for([]) returned VERIFIED because "every extent was confirmed" is trivially
    true of no extents. Correct logic, wrong word: VERIFIED reads as "checked and good",
    not "nothing happened". Found on real CFReDS L2/L3 -- the images NIST built to hold
    no contiguous file -- where the ledger was labelling a zero-recovery run VERIFIED.
    """
    assert outcome_for([]) == "PARTIAL"


def test_the_empty_case_still_uses_the_closed_vocabulary():
    from attestation.core import OUTCOMES
    assert outcome_for([]) in OUTCOMES
