#include "media/imager.hpp"
#include "media/map.hpp"
#include <fstream>
#include <algorithm>
#include <chrono>
namespace media {
static bool read_write(ISource&s,std::ofstream&o,std::uint64_t sec,std::uint32_t count,Policy p,Map&m,Stats&st){auto bytes=(size_t)count*m.sector_size;std::vector<std::byte>b(bytes);bool ok=s.read_at(sec*m.sector_size,b);st.attempts++;st.bytes_read+=bytes;if(ok){o.seekp((std::streamoff)(sec*m.sector_size));o.write((char*)b.data(),(std::streamsize)b.size());for(std::uint32_t i=0;i<count;i++)m.sectors[(size_t)(sec+i)].state=State::Good;return bool(o);}if(count>p.split_min_sectors){auto a=count/2;if(!read_write(s,o,sec,a,p,m,st)){}if(!read_write(s,o,sec+a,count-a,p,m,st)){}return true;}auto&x=m.sectors[(size_t)sec];x.attempts++;for(std::uint32_t r=0;r<p.retries;r++){std::vector<std::byte>one(m.sector_size);if(s.read_at(sec*m.sector_size,one)){o.seekp((std::streamoff)(sec*m.sector_size));o.write((char*)one.data(),(std::streamsize)one.size());x.state=State::Good;return bool(o);}x.attempts++;st.attempts++;}std::vector<std::byte>fill(m.sector_size,std::byte(p.fill));o.seekp((std::streamoff)(sec*m.sector_size));o.write((char*)fill.data(),(std::streamsize)fill.size());x.state=State::Failed;x.last_error=1;return bool(o);}
Result image(ISource&s,const std::string&dst,const std::string&map_path,Policy p,std::function<bool()>cancelled){Result r{};r.image=dst;r.map_path=map_path;r.map.sector_size=512;r.map.sector_count=(s.size()+511)/512;r.map.sectors.resize((size_t)r.map.sector_count);std::ofstream o(dst,std::ios::binary|std::ios::trunc);if(!o){r.status="destination_error";return r;}o.seekp((std::streamoff)(r.map.sector_count*512-1));o.put('\0');o.flush();for(std::uint64_t sec=0;sec<r.map.sector_count;){if(cancelled&&cancelled()){r.status="cancelled";save_map(r.map,map_path);return r;}auto n=(std::uint32_t)std::min<std::uint64_t>(p.block_sectors,r.map.sector_count-sec);read_write(s,o,sec,n,p,r.map,r.stats);sec+=n;save_map(r.map,map_path);}for(auto&x:r.map.sectors)x.state==State::Good?r.stats.good++:r.stats.failed++;r.status="complete";save_map(r.map,map_path);return r;}
}
