#include "raid/layout.hpp"
#include <fstream>
#include <algorithm>
namespace raid {
bool read_member(const std::unique_ptr<ISource>&s,std::uint64_t off,std::span<std::byte>b){return s&&s->read_at(off,b);}
static bool xor_into(std::span<std::byte>dst,const std::span<std::byte>src){if(dst.size()!=src.size())return false;for(size_t i=0;i<dst.size();i++)dst[i]=std::byte(std::to_integer<unsigned char>(dst[i])^std::to_integer<unsigned char>(src[i]));return true;}
Layout make_layout(Level l,std::uint32_t stripe,const std::vector<Member>&m){Layout x{};x.level=l;x.stripe_sectors=stripe;x.order.reserve(m.size());for(auto&q:m)x.order.push_back(q.index);auto chunk=(std::uint64_t)stripe*512;std::uint64_t minsz=~0ULL;for(auto&q:m)if(!q.missing)minsz=std::min(minsz,q.size);if(minsz==~0ULL)minsz=0;switch(l){case Level::R0:x.logical_size=minsz*m.size();x.score=40;break;case Level::R1:x.logical_size=minsz;x.score=45;break;case Level::R5:x.logical_size=minsz*(m.size()>0?m.size()-1:0);x.score=45;break;case Level::R6:x.logical_size=minsz*(m.size()>1?m.size()-2:0);x.score=45;break;case Level::R10:x.logical_size=minsz*(m.size()/2);x.score=45;break;case Level::Linear:x.logical_size=0;for(auto&q:m)x.logical_size+=q.size;x.score=35;break;}if(chunk==0)x.logical_size=0;x.evidence.push_back("explicit layout parameters");return x;}
static bool r0(const Layout&l,const std::vector<std::unique_ptr<ISource>>&s,std::uint64_t o,std::span<std::byte>b){auto chunk=(std::uint64_t)l.stripe_sectors*512;size_t done=0;while(done<b.size()){auto lo=o+done;auto stripe=lo/chunk;auto mi=stripe%s.size();auto in=lo%chunk;auto take=std::min<std::uint64_t>(chunk-in,b.size()-done);if(!read_member(s[mi],(stripe/s.size())*chunk+in,b.subspan(done,(size_t)take)))return false;done+=(size_t)take;}return true;}
static bool r1(const Layout&,const std::vector<std::unique_ptr<ISource>>&s,std::uint64_t o,std::span<std::byte>b){for(size_t i=0;i<s.size();i++)if(s[i]&&s[i]->size()>=o+b.size())return s[i]->read_at(o,b);return false;}
static size_t count_missing(const std::vector<std::unique_ptr<ISource>>&s){size_t m=0;for(auto&x:s)if(!x)m++;return m;}
// RAID5 tolerates exactly one missing member (reconstructed via parity XOR).
// Two or more missing members means the array is unrecoverable: refuse
// rather than silently substituting zero buffers for the extra missing
// disks, which would fabricate plausible-looking but wrong data.
static bool r5(const Layout&l,const std::vector<std::unique_ptr<ISource>>&s,std::uint64_t o,std::span<std::byte>b){auto n=s.size();if(n<3)return false;if(count_missing(s)>1)return false;auto chunk=(std::uint64_t)l.stripe_sectors*512;size_t done=0;while(done<b.size()){auto lo=o+done;auto stripe=lo/chunk;auto data_row=stripe/(n-1);auto pos=stripe%(n-1);auto parity=n-1-(data_row%n);auto disk=pos>=parity?pos+1:pos;auto member_off=data_row*chunk+lo%chunk;auto take=std::min<std::uint64_t>(chunk-lo%chunk,b.size()-done);if(s[disk]){if(!s[disk]->read_at(member_off,b.subspan(done,(size_t)take)))return false;}else{std::vector<std::byte>x((size_t)take);bool first=true;for(size_t d=0;d<n;d++){if(d==disk)continue;std::vector<std::byte>tmp((size_t)take);if(!s[d]||!s[d]->read_at(member_off,tmp))return false;if(first){x=tmp;first=false;}else xor_into(x,tmp);}std::copy(x.begin(),x.end(),b.begin()+done);}done+=(size_t)take;}return true;}
bool read_virtual(const Layout&l,const std::vector<std::unique_ptr<ISource>>&s,std::uint64_t o,std::span<std::byte>b){if(s.size()!=l.order.size())return false;if(o>l.logical_size||b.size()>l.logical_size-o)return false;switch(l.level){case Level::R0:return r0(l,s,o,b);case Level::R1:return r1(l,s,o,b);case Level::R5:return r5(l,s,o,b);case Level::R6:return read_raid6(l,s,o,b);case Level::R10:return read_raid10(l,s,o,b);default:return false;}}
bool export_virtual(const Layout&l,const std::vector<std::unique_ptr<ISource>>&s,std::uint64_t o,std::uint64_t n,const std::string&p,std::string&e){if(o>l.logical_size||n>l.logical_size-o){e="range outside virtual RAID";return false;}std::ofstream f(p,std::ios::binary);if(!f){e="cannot create export";return false;}std::vector<std::byte>b(1024*1024);std::uint64_t left=n,cur=o;while(left){auto take=(size_t)std::min<std::uint64_t>(left,b.size());if(!read_virtual(l,s,cur,std::span<std::byte>(b.data(),take))){e="virtual read failed";return false;}f.write((char*)b.data(),take);if(!f){e="export write failed";return false;}cur+=take;left-=take;}return true;}
}
