[package]
name = "drivewipe-gui"
version = "2.0.5"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
description = "Graphical UI for DriveWipe (iced framework)"

[dependencies]
crossbeam-channel.workspace = true
drivewipe-core = { path = "../drivewipe-core" }
iced.workspace = true
tokio.workspace = true
uuid.workspace = true
